export default [
  {
    name: "Student Belt",
    image: ``,
    description: ["Damage Resistance: +5%."],
    type: `Common`,
  },
  {
    name: "Armored Belt",
    image: ``,
    description: ["Max Armor: 100."],
    type: `Uncommon`,
  },
  {
    name: "Belt of Constitution",
    image: ``,
    description: ["Max Health: +25."],
    type: `Uncommon`,
  },
  {
    name: "Belt of Runic Speed",
    image: ``,
    description: ["Rune Cooldown Speed: +10%."],
    type: `Uncommon`,
  },
  {
    name: "Belt of Stone and Wind",
    image: ``,
    description: ["Stone Resistance: +30%", "Wind Resistance: +30%."],
    type: `Rare`,
  },
  {
    name: "Belt of Fire and Frost",
    image: ``,
    description: ["Fire Resistance: +30%", "Frost Resistance: +30%."],
    type: `Rare`,
  },
  {
    name: "Belt of Lightning and Toxic",
    image: ``,
    description: ["Lightning Resistance: +30%", "Toxic Resistance: +30%."],
    type: `Rare`,
  },
  {
    name: "Belt of Regeneration",
    image: ``,
    description: ["Regenerate Health: 3 Seconds/4 Seconds."],
    type: `Rare`,
  },
  {
    name: "Belt of Runic Study",
    image: ``,
    description: ["Max Rune Charges: +1."],
    type: `Rare`,
  },
  {
    name: "Reinforced Belt",
    image: ``,
    description: ["Armor Recovery Rate: +100%."],
    type: `Rare`,
  },
  {
    name: "Slaking Belt",
    image: ``,
    description: ["Consume Speed: +50%", "Health Recovery Rate: +100%."],
    type: `Epic`,
  },
  {
    name: "Belt of the Scribe",
    image: ``,
    description: [
      "One Rune Use: Damage Resistance: +95% (1s)",
      "Cooldown: 5 Seconds.",
    ],
    type: `Epic`,
  },
  {
    name: "Impenetrable Belt",
    image: ``,
    description: ["Damage Resistance: +20%."],
    type: `Epic`,
  },
  {
    name: "Behemoth Belt",
    image: ``,
    description: ["Max Armor: +50", "Max Health: 25", "Max Rune Charges: +1."],
    type: `Legendary`,
  },
  {
    name: "Belt of Runic Fluency",
    image: ``,
    description: ["Max Rune Charges: +2", "Rune Cooldown Speed: +20%."],
    type: `Legendary`,
  },
]
